#!/usr/bin/env python3
"""
Scaffold a newsletter site under <dir>.

Usage:
    python init_site.py --dir ./site --design minimal --title "AI Newsletter"

The skill invokes this once during Phase 0. It creates the directory skeleton,
copies the chosen design.md, renders a placeholder style.css from the design
tokens, and writes an empty sources.yaml + site.yaml.

Re-running on an existing site is safe: it only creates missing files.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent.parent  # .../ai-newsletter-builder
BUILTIN_DESIGNS = SKILL_DIR / "designs"


def slurp(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def parse_design(md: str) -> dict:
    """Very small parser for the design.md contract. Extracts:
    - tokens dict (from '## Tokens' bullet list)
    - category_colors dict (from '## Category colors' bullet list)
    - hero snippet (content under '## Hero' up to next heading) or None
    - custom_css (content under '## Custom CSS') or None
    """
    sections: dict[str, str] = {}
    current: str | None = None
    buf: list[str] = []
    for line in md.splitlines():
        m = re.match(r"^(#{1,3})\s+(.*)$", line)
        if m and len(m.group(1)) == 2:
            if current is not None:
                sections[current] = "\n".join(buf).strip()
            current = m.group(2).strip()
            buf = []
            continue
        buf.append(line)
    if current is not None:
        sections[current] = "\n".join(buf).strip()

    def parse_bullets(key: str) -> dict[str, str]:
        body = sections.get(key, "")
        out: dict[str, str] = {}
        for ln in body.splitlines():
            m = re.match(r"^-\s+([A-Za-z0-9_-]+):\s+(.+?)\s*$", ln)
            if m:
                out[m.group(1)] = m.group(2).strip()
        return out

    tokens = parse_bullets("Tokens")
    categories = parse_bullets("Category colors")
    hero = sections.get("Hero") or None
    custom_css = sections.get("Custom CSS") or None
    return {
        "tokens": tokens,
        "categories": categories,
        "hero": hero,
        "custom_css": custom_css,
    }


BASE_CSS = """/* Generated by init_site.py — do not edit by hand. Regenerate by re-running init. */
:root {
  --bg: __BACKGROUND__;
  --surface: __SURFACE__;
  --ink: __INK__;
  --ink-muted: __INK_MUTED__;
  --accent: __ACCENT__;
  --accent-soft: __ACCENT_SOFT__;
  --divider: __DIVIDER__;
  --radius: __RADIUS__px;
  --max-w: __MAX_WIDTH__px;
  --font-body: __FONT_BODY__;
  --font-display: __FONT_DISPLAY__;
  --font-mono: __FONT_MONO__;

  --cat-major-release: __CAT_MAJOR_RELEASE__;
  --cat-industry-business: __CAT_INDUSTRY_BUSINESS__;
  --cat-research-frontier: __CAT_RESEARCH_FRONTIER__;
  --cat-tools-release: __CAT_TOOLS_RELEASE__;
  --cat-policy-regulation: __CAT_POLICY_REGULATION__;
}

* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; }
body {
  background: var(--bg);
  color: var(--ink);
  font-family: var(--font-body);
  -webkit-font-smoothing: antialiased;
  line-height: 1.6;
}
main { max-width: var(--max-w); margin: 0 auto; padding: 32px 24px 80px; }
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
hr { border: 0; border-top: 1px solid var(--divider); margin: 32px 0; }

h1, h2, h3 { font-family: var(--font-display); line-height: 1.3; margin-top: 0; }
h1 { font-size: 36px; }
h2 { font-size: 22px; margin-top: 40px; }
h3 { font-size: 18px; margin-top: 24px; }
p { margin: 0 0 12px; }
small { color: var(--ink-muted); font-size: 13px; }

.site-header { border-bottom: 1px solid var(--divider); padding: 20px 0; margin-bottom: 24px; }
.site-header a { color: var(--ink); font-weight: 600; }

.issue-list { list-style: none; padding: 0; margin: 0; }
.issue-list li { border-bottom: 1px solid var(--divider); padding: 18px 0; }
.issue-list li:last-child { border-bottom: 0; }
.issue-list time { color: var(--ink-muted); font-size: 13px; font-family: var(--font-mono); display: block; margin-bottom: 6px; }
.issue-list h3 a { color: var(--ink); }
.issue-list .teaser { color: var(--ink-muted); margin: 6px 0 10px; }
.issue-list .category-tags { display: flex; flex-wrap: wrap; gap: 8px; margin: 8px 0; }
.issue-list .top-item-list { list-style: none; padding: 0; margin: 12px 0 0; }
.issue-list .top-item-list li { padding: 6px 0; display: flex; flex-wrap: wrap; gap: 8px; align-items: baseline; border: 0; }
.issue-list .top-item-list li a { color: var(--ink); }

.category-tag { font-size: 11px; padding: 2px 8px; border-radius: 999px; background: var(--accent-soft); color: var(--accent); display: inline-block; }
.category-tag[data-slug="major-release"] { background: color-mix(in srgb, var(--cat-major-release) 15%, transparent); color: var(--cat-major-release); }
.category-tag[data-slug="industry-business"] { background: color-mix(in srgb, var(--cat-industry-business) 15%, transparent); color: var(--cat-industry-business); }
.category-tag[data-slug="research-frontier"] { background: color-mix(in srgb, var(--cat-research-frontier) 15%, transparent); color: var(--cat-research-frontier); }
.category-tag[data-slug="tools-release"] { background: color-mix(in srgb, var(--cat-tools-release) 15%, transparent); color: var(--cat-tools-release); }
.category-tag[data-slug="policy-regulation"] { background: color-mix(in srgb, var(--cat-policy-regulation) 15%, transparent); color: var(--cat-policy-regulation); }

.source-badge { font-size: 11px; color: var(--ink-muted); margin-left: 8px; font-family: var(--font-mono); }

article.item { border-bottom: 1px solid var(--divider); padding: 20px 0; }
article.item:last-child { border-bottom: 0; }
article.item h3 { margin: 0 0 4px; font-size: 18px; line-height: 1.35; }
article.item h3 a { color: var(--ink); }
article.item .meta { color: var(--ink-muted); font-size: 12px; margin-top: 6px; }
article.item details summary { cursor: pointer; color: var(--ink-muted); font-size: 12px; margin-top: 6px; }
article.item details ul { margin: 6px 0 0; padding-left: 18px; }

.category { margin-top: 40px; }
.category > h2 { display: flex; align-items: center; gap: 10px; }
.category__count { color: var(--ink-muted); font-size: 13px; font-weight: 400; }

.site-footer { margin-top: 80px; padding: 24px 0; border-top: 1px solid var(--divider); color: var(--ink-muted); font-size: 13px; text-align: center; }
"""


def render_css(design: dict) -> str:
    t = design["tokens"]
    c = design["categories"]

    def g(d: dict, k: str, default: str = "") -> str:
        return d.get(k, default)

    replacements = {
        "__BACKGROUND__": g(t, "background", "#fff"),
        "__SURFACE__": g(t, "surface", "#fff"),
        "__INK__": g(t, "ink", "#111"),
        "__INK_MUTED__": g(t, "ink-muted", "#666"),
        "__ACCENT__": g(t, "accent", "#0F62FE"),
        "__ACCENT_SOFT__": g(t, "accent-soft", "#E5EEFF"),
        "__DIVIDER__": g(t, "divider", "#EEE"),
        "__RADIUS__": g(t, "radius", "8"),
        "__MAX_WIDTH__": g(t, "max-width", "760"),
        "__FONT_BODY__": g(t, "font-body", "system-ui, sans-serif"),
        "__FONT_DISPLAY__": g(t, "font-display", "system-ui, sans-serif"),
        "__FONT_MONO__": g(t, "font-mono", "monospace"),
        "__CAT_MAJOR_RELEASE__": g(c, "major-release", "#0F62FE"),
        "__CAT_INDUSTRY_BUSINESS__": g(c, "industry-business", "#047857"),
        "__CAT_RESEARCH_FRONTIER__": g(c, "research-frontier", "#7C3AED"),
        "__CAT_TOOLS_RELEASE__": g(c, "tools-release", "#B45309"),
        "__CAT_POLICY_REGULATION__": g(c, "policy-regulation", "#B91C1C"),
    }
    css = BASE_CSS
    for k, v in replacements.items():
        css = css.replace(k, v)
    if design.get("custom_css"):
        css += "\n/* === custom css from design.md === */\n" + design["custom_css"] + "\n"
    return css


SOURCES_YAML_HEADER = """# Data sources for the newsletter.
# See the skill's references/data_sources.md for field documentation and the
# built-in source catalog.
#
# Each source collects into site/data/raw/<date>/<name>.md.

sources: []
"""


def render_site_yaml(title: str, design: str, output_language: str) -> str:
    return f"""# Site-level configuration.
title: "{title}"
subtitle: "每日 AI 资讯精选"
output_language: {output_language}   # zh | en — used for rendered summaries & lead
timezone: Asia/Shanghai
design: {design}                    # name of built-in design or path to custom design.md
hero_on_homepage: true
"""


def render_readme(title: str) -> str:
    return f"""# {title}

Generated by the `ai-newsletter-builder` skill.

- `index.html` — homepage, regenerated by `scripts/build_index.py`.
- `issues/<date>.html` — one file per daily issue.
- `data/issues.json` — lightweight manifest used by the homepage.
- `config/sources.yaml` — data source definitions.
- `config/design.md` — active design system.

## Rebuild the homepage

```bash
python <path-to-skill>/scripts/build_index.py --site .
```

## Publish

See the skill's `references/publish.md` for GitHub Pages and Cloudflare Pages instructions.
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", required=True, help="Site directory to create/populate")
    ap.add_argument("--design", default="minimal", help="Built-in design name or path to custom design.md")
    ap.add_argument("--title", default="AI Newsletter", help="Site title")
    ap.add_argument("--lang", default="zh", choices=["zh", "en"], help="Output language for summaries")
    args = ap.parse_args()

    site = Path(args.dir).resolve()
    site.mkdir(parents=True, exist_ok=True)

    # Resolve design — two formats:
    #   1) legacy single-file .md (tokens-only) → templated CSS gen
    #   2) directory containing DESIGN.md (Google Stitch / getdesign.md) → placeholder CSS; model must regenerate
    design_arg = args.design
    design_format: str
    design_src: Path

    arg_path = Path(design_arg)
    if arg_path.is_file():
        design_src = arg_path.resolve()
        design_format = "legacy"
    elif arg_path.is_dir() and (arg_path / "DESIGN.md").is_file():
        design_src = arg_path.resolve()
        design_format = "design_md"
    else:
        # Try built-in: directory first, then legacy .md
        builtin_dir = BUILTIN_DESIGNS / design_arg
        builtin_file = BUILTIN_DESIGNS / f"{design_arg}.md"
        if builtin_dir.is_dir() and (builtin_dir / "DESIGN.md").is_file():
            design_src = builtin_dir
            design_format = "design_md"
        elif builtin_file.is_file():
            design_src = builtin_file
            design_format = "legacy"
        else:
            legacy = [p.stem for p in BUILTIN_DESIGNS.glob("*.md") if p.is_file()]
            stitch = [p.name for p in BUILTIN_DESIGNS.iterdir() if p.is_dir() and (p / "DESIGN.md").is_file()]
            print(
                f"error: design '{design_arg}' not found.\n"
                f"  legacy designs (.md):   {', '.join(legacy) or '(none)'}\n"
                f"  DESIGN.md designs (dir): {', '.join(stitch) or '(none)'}",
                file=sys.stderr,
            )
            return 2

    # Create subdirs
    for sub in ("assets", "issues", "data", "data/raw", "config"):
        (site / sub).mkdir(parents=True, exist_ok=True)

    # Copy the chosen design into site/config/
    if design_format == "legacy":
        # Single-file: site/config/design.md + templated style.css
        design_dst = site / "config" / "design.md"
        if not design_dst.exists():
            shutil.copy(design_src, design_dst)
        design = parse_design(slurp(design_dst))
        (site / "assets" / "style.css").write_text(render_css(design), encoding="utf-8")
    else:
        # DESIGN.md directory: site/config/design/<name>/ + placeholder style.css
        dest_dir = site / "config" / "design" / design_src.name
        if not dest_dir.exists():
            shutil.copytree(design_src, dest_dir)
        placeholder = f"""/* Placeholder CSS — overwritten when the skill regenerates from DESIGN.md.
 * Active design: {design_src.name}/DESIGN.md
 * Do NOT edit by hand. Regenerate via the skill.
 */
:root {{
  --color-ink: #111;
  --color-bg: #fff;
  --color-accent: #0F62FE;
  --font-body: system-ui, sans-serif;
  --max-w: 760px;
}}
body {{ margin: 0; background: var(--color-bg); color: var(--color-ink); font-family: var(--font-body); line-height: 1.6; }}
main {{ max-width: var(--max-w); margin: 0 auto; padding: 32px 24px 80px; }}
h1 {{ font-size: 32px; }}
h2 {{ font-size: 22px; margin-top: 40px; }}
h3 {{ font-size: 18px; }}
a {{ color: var(--color-accent); }}
/* TODO: the skill must regenerate this CSS by reading DESIGN.md — until then, the site will look unstyled. */
"""
        (site / "assets" / "style.css").write_text(placeholder, encoding="utf-8")

    # Write site.yaml if missing
    site_yaml = site / "config" / "site.yaml"
    if not site_yaml.exists():
        site_yaml.write_text(
            render_site_yaml(args.title, design_arg if "/" not in design_arg else "custom", args.lang),
            encoding="utf-8",
        )

    # Write sources.yaml if missing
    sources_yaml = site / "config" / "sources.yaml"
    if not sources_yaml.exists():
        sources_yaml.write_text(SOURCES_YAML_HEADER, encoding="utf-8")

    # Initialize issues.json if missing
    issues_json = site / "data" / "issues.json"
    if not issues_json.exists():
        issues_json.write_text(json.dumps({"issues": [], "generated_at": datetime.now(timezone.utc).isoformat()}, indent=2), encoding="utf-8")

    # README
    readme = site / "README.md"
    if not readme.exists():
        readme.write_text(render_readme(args.title), encoding="utf-8")

    print(f"✓ site scaffolded at: {site}")
    print(f"  design: {design_src.name} ({design_format})")
    print(f"  title:  {args.title}")
    print(f"  lang:   {args.lang}")
    if design_format == "design_md":
        print("\n⚠️  DESIGN.md format detected — placeholder CSS was written.")
        print(f"    Next: read {design_src.name}/DESIGN.md and regenerate")
        print(f"    site/assets/style.css (see references/design_md_guide.md).")
    print("\nNext steps:")
    print(f"  1) edit {sources_yaml.relative_to(site.parent)} to add sources")
    print(f"  2) generate today's issue via the skill")
    print(f"  3) run build_index.py to refresh the homepage")
    return 0


if __name__ == "__main__":
    sys.exit(main())
